spring.application.name=API
spring.datasource.url=jdbc:h2:mem:apidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
server.error.include-message=always